<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>block icon</name>
   <tag></tag>
   <elementGuidId>cb8217a3-9590-44a6-9a22-947503cfcda9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;h-100&quot;]/jb-app[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;flex flex-column flex-row-m flex-row-l&quot;]/div[@class=&quot;flex flex-column items-center flex-auto pt4 pt0-ns w-100 h-100 ng-trigger ng-trigger-pushContent&quot;]/main[@class=&quot;h-100 bg-white charcoal pt7-ns center&quot;]/cb-cookbook-related-content-block[@class=&quot;ng-star-inserted&quot;]/cb-section[@class=&quot;db&quot;]/section[@class=&quot;page-margin&quot;]/cb-example[1]/div[@class=&quot;db pb0 mt4 mb5&quot;]/div[@class=&quot;pv3&quot;]/div[@class=&quot;mb5&quot;]/jb-related-content-block[1]/jb-related-content-block-grid-container[@class=&quot;jb-grid&quot;]/section[@class=&quot;pa0 col-12 col-11-m col-9-l&quot;]/div[@class=&quot;br-rounded-4 bg-off-white b--medium-gray ba ph4 pv3&quot;]/jb-related-content-block-section-specific[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;flex flex-column flex-row-ns justify-start&quot;]/div[@class=&quot;db icon-container flex items-center mb2 mb0-ns mr4-ns&quot;]/jb-icon[@class=&quot;t-fast notranslate&quot;]/svg[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>72</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>72</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 72 72</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;h-100&quot;]/jb-app[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;flex flex-column flex-row-m flex-row-l&quot;]/div[@class=&quot;flex flex-column items-center flex-auto pt4 pt0-ns w-100 h-100 ng-trigger ng-trigger-pushContent&quot;]/main[@class=&quot;h-100 bg-white charcoal pt7-ns center&quot;]/cb-cookbook-related-content-block[@class=&quot;ng-star-inserted&quot;]/cb-section[@class=&quot;db&quot;]/section[@class=&quot;page-margin&quot;]/cb-example[1]/div[@class=&quot;pb0 mt4 mb5&quot;]/div[@class=&quot;pv3&quot;]/div[@class=&quot;mb5&quot;]/jb-related-content-block[1]/jb-related-content-block-grid-container[@class=&quot;jb-grid&quot;]/section[@class=&quot;pa0 col-12 col-11-m col-9-l&quot;]/div[@class=&quot;br-rounded-4 bg-off-white b--medium-gray ba ph4 pv3&quot;]/jb-related-content-block-section-specific[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;flex flex-column flex-row-ns justify-start&quot;]/div[@class=&quot;db icon-container flex items-center mb2 mb0-ns mr4-ns&quot;]/jb-icon[@class=&quot;t-fast notranslate&quot;]/svg[1]</value>
   </webElementProperties>
</WebElementEntity>
