<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_concat(id(  tic-tac-toe</name>
   <tag></tag>
   <elementGuidId>7659a375-dbd0-44dc-89d1-cee761e5a337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='tic-tac-toe-board']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tic-tac-toe-board&quot;)[count(. | //canvas[@id = 'tic-tac-toe-board' and @class = 'center-v' and @width = '500' and @height = '500' and @ref_element = 'Object Repository/Temporary/Page_CodePen - Tic Tac Toe board us/iframe_Edit Pen_result']) = count(//canvas[@id = 'tic-tac-toe-board' and @class = 'center-v' and @width = '500' and @height = '500' and @ref_element = 'Object Repository/Temporary/Page_CodePen - Tic Tac Toe board us/iframe_Edit Pen_result'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tic-tac-toe-board</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>center-v</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tic-tac-toe-board&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Temporary/Page_CodePen - Tic Tac Toe board us/iframe_Edit Pen_result</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//canvas[@id='tic-tac-toe-board']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'tic-tac-toe-board', '&quot;', ')')])[1]/preceding::canvas[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//canvas</value>
   </webElementXpaths>
</WebElementEntity>
