<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_toListMonths</name>
   <tag></tag>
   <elementGuidId>278b2b15-6fe2-4c8f-ba22-c3c0ace60d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white w-100 flex flex-row items-center avenir lh-copy pointer justify-center tl pa0 b bn royal-blue hover-core-blue hover-fill-core-blue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> November  November </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;h-100&quot;]/body[@class=&quot;h-100&quot;]/jb-app[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;flex flex-column flex-row-m flex-row-l&quot;]/div[@class=&quot;flex flex-column items-center flex-auto pt4 pt0-ns w-100 h-100 ng-trigger ng-trigger-pushContent&quot;]/main[@class=&quot;h-100 bg-white charcoal pt7-ns center&quot;]/cb-editorial-grid[@class=&quot;ng-star-inserted&quot;]/cb-example[1]/div[@class=&quot;pb0 mt4 mb5&quot;]/div[@class=&quot;pv3 page-margin&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/jb-editorial-grid[@id=&quot;editorial-grid-component&quot;]/div[@class=&quot;flex justify-center&quot;]/section[@class=&quot;flex flex-wrap w-100&quot;]/jb-editorial-weather-widget[@class=&quot;relative relative db w-100 w-50-m w-third-l&quot;]/section[@class=&quot;w-100 h-inherit relative&quot;]/div[@class=&quot;flex justify-center items-center h-100 w-100 relative&quot;]/div[@class=&quot;bg-white inner-container br-75 pa4 pb5&quot;]/div[@class=&quot;flex flex-column justify-between h-100&quot;]/jb-select[@class=&quot;relative db ng-tns-c11-1 simple-select ng-untouched ng-valid ng-dirty&quot;]/button[@class=&quot;bg-white w-100 flex flex-row items-center avenir lh-copy pointer justify-center tl pa0 b bn royal-blue hover-core-blue hover-fill-core-blue&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//button[@type='button']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//jb-editorial-grid[@id='editorial-grid-component']/div/section/jb-editorial-weather-widget/section/div/div/div/jb-select/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly average temperature'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='°F'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//jb-select/button</value>
   </webElementXpaths>
</WebElementEntity>
